stages:
  - deploy

variables:
  NODE_VERSION: "18.17.0"
  NPM_REGISTRY_WP: "@wpmedia:registry=https://npm.pkg.github.com/"
  NPM_REGISTRY_ARCXP: "@arcxp:registry=https://npm.pkg.github.com/"
default:
  tags:
    - gitlab-runner-ec2
cache:
  paths:
    - node_modules
  key: node-modules-$CI_COMMIT_REF_SLUG-$CI_JOB_NAME

deploy:
  stage: deploy
  image: node:$NODE_VERSION
  script:
    - echo "$NPM_REGISTRY_WP" >> .npmrc
    - echo "$NPM_REGISTRY_ARCXP" >> .npmrc
    - echo "//npm.pkg.github.com/:_authToken=$CI_JOB_TOKEN" >> .npmrc
    - npm ci
    - node deployer.mjs
  environment:
    name: production
