# deploy para branch main
# main -> (e2e depois) -> Sandbox
# create tag
# tag -> Staging -> Prod

variables:
  NODE_VERSION: node:18
  CI: 'true'
  GIT_DEPTH: 0

image: $NODE_VERSION

default:
  services:
    - docker:dind
  tags:
    - gitlab-runner-ec2
  
stages: 
  - lint
  - deploy-sandbox

lint:     
  stage: lint
  services:
    - docker:dind
  script:
    - docker container list 
    - echo "Linting..."

deploy-sandbox:
  stage: deploy-sandbox
  script:
    - npx fusion zip
    - npm run deploy