# deploy para branch main
# main -> (e2e depois) -> Sandbox
# create tag
# tag -> Staging -> Prod

variables:
  NODE_VERSION: washpost/fusion-engine:3.3.7
  CI_DEBUG_TRACE: "true"

image: $NODE_VERSION

default:
  tags:
    - gitlab-runner-ec2
  
stages: 
  - lint
  - deploy-sandbox

lint:     
  stage: lint  
  script:
    - echo "Linting..."

deploy-sandbox:
  stage: deploy-sandbox
  script:
    - ls
    - pwd
    - npm run zip
    - npm run deploy